# Generated by Django 6.0.2 on 2026-02-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Show in Flash Sales section'),
        ),
    ]
