# Generated by Django 6.0.2 on 2026-02-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False, help_text='Show in Best Selling Products section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_explore',
            field=models.BooleanField(default=False, help_text='Show in Explore Our Products section'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, help_text='Show in New Arrival section'),
        ),
    ]
