# Generated by Django. Add initial migration for ProductReview model.
from django.db import migrations

def set_default_related_products(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        product.related_products.set([])
        product.save()

class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_productreview'),
    ]
    operations = [
        migrations.RunPython(set_default_related_products),
    ]
