# Generated by Django 6.0.2 on 2026-02-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_link',
            field=models.URLField(blank=True, help_text='Optional external image URL.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True, help_text='Optional external image URL.', null=True),
        ),
    ]
